upgraded Oracle JDK to 7u65

diff --git a/ubuntu/tomcat7-oracle/Dockerfile b/ubuntu/tomcat7-oracle/Dockerfile
--- a/ubuntu/tomcat7-oracle/Dockerfile
+++ b/ubuntu/tomcat7-oracle/Dockerfile
@@ -6,13 +6,13 @@ RUN apt-get update
 ENV TOMCATVER 7.0.55
 
 RUN DEBIAN_FRONTEND=noninteractive apt-get -y install patch wget
-RUN (wget --progress=dot --no-check-certificate -O /tmp/server-jre-7u51-linux-x64.tar.gz --header "Cookie: oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/server-jre-7u51-linux-x64.tar.gz && \
-        echo "c5a034f4222bac326101799bcb20509c  /tmp/server-jre-7u51-linux-x64.tar.gz" | md5sum -c > /dev/null 2>&1 || echo "ERROR: MD5SUM MISMATCH" && \
-        tar xzf /tmp/server-jre-7u51-linux-x64.tar.gz && \
-        mkdir -p /usr/lib/jvm/java-7-oracle && \
-        mv jdk1.7.0_51/jre /usr/lib/jvm/java-7-oracle/jre && \
-        rm -rf jdk1.7.0_51 && rm /tmp/server-jre-7u51-linux-x64.tar.gz && \
-        chown root:root -R /usr/lib/jvm/java-7-oracle)
+RUN (wget --progress=dot --no-check-certificate -O /tmp/server-jre-7u65-linux-x64.tar.gz --header "Cookie: oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/7u65-b17/jdk-7u65-linux-x64.tar.gz && \
+	echo "c223bdbaf706f986f7a5061a204f641f  /tmp/server-jre-7u65-linux-x64.tar.gz" | md5sum -c > /dev/null 2>&1 || echo "ERROR: MD5SUM MISMATCH" && \
+	tar xzf /tmp/server-jre-7u65-linux-x64.tar.gz && \
+	mkdir -p /usr/lib/jvm/java-7-oracle && \
+	mv jdk1.7.0_65/jre /usr/lib/jvm/java-7-oracle/jre && \
+	rm -rf jdk1.7.0_65 && rm /tmp/server-jre-7u65-linux-x64.tar.gz && \
+	chown root:root -R /usr/lib/jvm/java-7-oracle)
 RUN (update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-7-oracle/jre/bin/java 1 && update-alternatives --set java /usr/lib/jvm/java-7-oracle/jre/bin/java)
 
 RUN (wget -O /tmp/tomcat7.tar.gz http://mirror.cogentco.com/pub/apache/tomcat/tomcat-7/v${TOMCATVER}/bin/apache-tomcat-${TOMCATVER}.tar.gz && \
